{"name": "test_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test_demo.TestDemo object at 0x00000267AD8C3100>\n\n    def test_b(self):\n>       assert False\nE       assert False\n\nscripts\\test_demo.py:7: AssertionError"}, "start": 1742621684737, "stop": 1742621684737, "uuid": "8f083c97-0998-420f-8f9b-741c20509d22", "historyId": "5e07166ce6f2b0b33def3cb4bf5a75a0", "testCaseId": "5e07166ce6f2b0b33def3cb4bf5a75a0", "fullName": "scripts.test_demo.TestDemo#test_b", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "TestDemo"}, {"name": "host", "value": "ZhangGui"}, {"name": "thread", "value": "24404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_demo"}]}